# Config for https://github.com/apps/release-drafter
name-template: 'v$NEXT_MINOR_VERSION (Optional summary)'
tag-template: 'v$NEXT_MINOR_VERSION'
template: |
  ## Changes

  $CHANGES

  ## Upgrading

  To upgrade, update your `pipeline.yml` files:

  ```diff
  steps:
    - plugins:
  -     liamdawson/convox-run#$PREVIOUS_TAG:
  +     liamdawson/convox-run#v$NEXT_MINOR_VERSION:
          app: someapp
          rack: somerack
          command: echo 'Hello, world!'
  ```
